### ISSUE TITLE
ROS2 Control Tag Example

### ISSUE THREAD

**Issue by nishalangovender** [acfr/roboteq_driver#1]
Hi!

May an example on the use of the driver either be added to the README or included as an example (in another ROS2 package or in tests)? Specifically, the use of the driver in the ROS2 control tag (hardware interface plugin name with parameters and use of joints with parameters).

**Comment by jclinton830** [comment]
@nishalangovender this package is still under development. It doesn't fully work. Once it is ready we will publish some information about how to use it.
